### ISSUE TITLE
Update wornApps with bound apps, player currently not updating worn when moving

### ISSUE THREAD

**Issue by lalalune** [TheNexusCity/webaverse-app#80]
![image](https://user-images.githubusercontent.com/18633264/168511647-bfc1f999-277b-43e7-a4ff-31ec10c088a5.png)

If I leave and come back then my wornApps is erased so nothing updates

**Comment by DavinciDreams** [comment]
Related? https://github.com/webaverse/app/issues/1825#

The lantern wearing (grabbing) crashes because the lantern is part of a group and independently controlled, but it is not part of the player's app manager. Therefore the wear logic cannot find the app by its instance id; it is not tracked anywhere besides the group.

To solve this we need to either:

make sure that only the top level group object is grabbed, it shouldn't know about the children, and the children can just get tehir state downstream
we can make a new app manager for these internal sub cases, collect these apps there, and then look there for lookup during the wear logic
My vote is for 1).

Lantern app: https://github.com/webaverse/lantern
Where the lookup fails:

[app/player-avatar-binding.js](https://github.com/webaverse/app/blob/6e4c66a2de41cf72ec7fc6dcca75bcab54dacdd6/player-avatar-binding.js#L30)

Line 30 in [6e4c66a](https://github.com/webaverse/app/commit/6e4c66a2de41cf72ec7fc6dcca75bcab54dacdd6)

 const app = player.appManager.getAppByInstanceId(action.instanceId); 

Where the lantern subapp is created: https://github.com/webaverse/metaversefile/blob/9fa1000110181c91d2f76a9b4fadc3a7c4187606/type_templates/group.js#L93
@[ahadshams](https://github.com/ahadshams) ahadshams assigned [skaljac](https://github.com/skaljac) [on Nov 17, 2021](https://github.com/webaverse/app/issues/1825#event-5634937234)
@[skaljac](https://github.com/skaljac) skaljac mentioned this issue [on Dec 22, 2021](https://github.com/webaverse/app/issues/1825#ref-pullrequest-1087252352)
https://github.com/webaverse/app/pull/2061
 Merged
@[alisaad673](https://github.com/alisaad673) alisaad673 mentioned this issue [on Dec 29, 2021](https://github.com/webaverse/app/issues/1825#ref-issue-1071282252)
https://github.com/webaverse/app/issues/1926
